apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq1
  namespace: mq
spec:
  license:
    accept: true
    license: L-RJON-BZFQU2
   # license: L-RJON-BN7PN3
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    image: cp.icr.io/cp/ibm-mqadvanced-server-integration:9.2.3.0-r1-amd64
    imagePullPolicy: Always
    storage:
      queueManager:
        enabled: true
    availability:
      type: SingleInstance
    #  type: NativeHA
    name: QM1
    mqsc:
    - configMap:
        name: mq1-mqsc
        items:
        - ivt.mqsc
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.2.3.0-r1
 # version: 9.2.0.0-r1
  web:
    enabled: true
  tracing:
    enabled: true
    namespace: ops-dash
  pki:
    keys:
      - name: label1
        secret:
          secretName: mq1key
          items:
            - tls.key
            - tls.crt
  imagePullSecrets:
    - name: ibm-entitlement-key
