apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq1
  namespace: mq
spec:
  mqDashboard: true
  license:
    accept: true
    #license: L-RJON-BZFQU2
    license: L-RJON-CD3JKX
    metric: VirtualProcessorCore
    use: NonProduction
  queueManager:
    #image: cp.icr.io/cp/ibm-mqadvanced-server-integration:9.3.0.1-r1-amd64
    imagePullPolicy: Always
    storage:
      defaultClass: ibmc-block-gold
      persistedData:
        enabled: true
        type: persistent-claim
      queueManager:
        type: persistent-claim
      recoveryLogs:
        class: ibmc-block-gold
        enabled: true
        type: persistent-claim
    availability:
      #type: MultiInstance
      #type: SingleInstance
      type: NativeHA
    metrics:
      enabled: true
    resources:
      limits:
        cpu: '1'
        memory: 2Gi
      requests:
        cpu: '1'
        memory: 2Gi
    name: QM1
    mqsc:
    - configMap:
        name: mq1-mqsc
        items:
        - ivt.mqsc
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  version: 9.3.0.3-r1
  web:
    enabled: false
  tracing:
    enabled: false
    namespace: od
    # collector:
      # image: cp.icr.io/cp/icp4i/od/icp4i-od-collector:2.5.0-amd64@sha256:44460e67780a4166a07a36da10260d9497526afdd899af9ad745ac6197e92ca6
  pki:
    keys:
      - name: label1
        secret:
          secretName: mq1key
          items:
            - tls.key
            - tls.crt
    trust:
      - name: trust1
        secret:
          secretName: tls-eris-trust
          items:
            - CSQ9.crt
  imagePullSecrets:
    - name: ibm-entitlement-key
